# Website's icon url.
favicon: /favicon.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id: Lei_Wang_1999
  twitter_site: https://twitter.com/Lei_Wang_1999
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo:
  text: "Lei::Blog"

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: xt256
  # Date format: relative | full | relative_full | full_relative
  date_format: relative
  readmore: 'read more'


# Navigation bar menu links.
menu:
  Home: /
  # Categories: categories
  Tags: tags
  # Material: material
  # Games: games
  About: about

# Search plugin settings.
search:
  type: insight


# Navigation bar toc settings
toc: true

# Share plugin settings.
# share:
#   type: sharethis
#   install_url:

# Comment plugin settings.
comment:
  type: valine
  serverURL: https://vtjojtao.api.lncldglobal.com
  avatar: retro
  app_id: vTjojtAolevJ2QEt3Ig8gEKD-MdYXbMMI # (required) LeanCloud application id
  app_key: Ylh2i3sM1fEJrejGuujx52Ja # (required) LeanCloud application key
  notify: true # (optional) receive email notification
  verify: false # (optional) show verification code
  placeholder: "Happy for sharing!" # (optional) comment box placeholder text

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: true
  gallery: true
  clipboard: true
  # google-analytics:
  #   tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/LeiWang1999

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/LeiWang1999

share:
  type: addthis
  install_url: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5f042ecc0064f551 # (required)
